# Define the HTTP settings
httpClient:
  port: 8080
  adminPort: 8081

# Define the client settings for connecting to upstream data services
httpClient:
  timeout: 60s # Timeout while connecting, reading, or writing (Heroku needs large value for spin-up)
  timeToLive: 10m # Keep connections open
  cookiesEnabled: true # Track cookies
  gzipEnabled: true # Allow for gzipped request and response entities
  minThreads: 1
  maxThreads: 128 # Thread pool for JerseyClient's async requests

logging:

  level: WARN

  # Logger-specific levels.
  loggers:

    # Set specific levels
    "com.sun.jersey.api.client": DEBUG
    "io.dropwizard": INFO
    "${groupId}": DEBUG

#
privateKeyFile:
  D:/dev/workspaces/personale/rest-ms/auth-service/src/test/java/private.key
publicKeyFile:
  D:/dev/workspaces/personale/rest-ms/auth-service/src/test/java/public.key